# -*- coding: utf-8 -*-
"""Central_limit_theorem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E53VbdMz8bUsCu-zz3e-H3CyaJJbh6I3
"""

#  Central Limit Theorem (CLT)

##  Objective
# To demonstrate how the sampling distribution of the sample mean becomes approximately normal,
# even when the population distribution is skewed.

##  Concept
# The Central Limit Theorem states that for a sufficiently large sample size (n ≥ 30),
# the sampling distribution of the mean approaches a normal distribution regardless of the population distribution.

##  Key Insight
# "CLT normalizes averages, not raw data."

import numpy as np
import matplotlib.pyplot as plt

# Create skewed population data
population = np.array([
    5, 7, 8, 12, 15, 20, 25, 30, 35, 40,
    45, 50, 60, 70, 80, 90, 100, 120, 150, 200
])

print("Population Data:")
print(population)

##  Step 1: Visualizing Original Population

# The population data is skewed and not normally distributed.
plt.figure()
plt.hist(population, bins=10)
plt.title("Original Population Distribution (Skewed)")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

## Step 2: Generate Sampling Distribution

# We take multiple samples and compute their means.
sample_size = 30
num_samples = 1000

sample_means = []

for _ in range(num_samples):
    sample = np.random.choice(population, size=sample_size, replace=True)
    sample_means.append(np.mean(sample))

print("First 10 Sample Means:", sample_means[:10])

# ## 📊 Step 3: Sampling Distribution of Sample Means

# According to CLT, this should form a normal distribution.
plt.figure()
plt.hist(sample_means, bins=30)
plt.title("Sampling Distribution of Sample Means (CLT)")
plt.xlabel("Sample Mean")
plt.ylabel("Frequency")
plt.show()

##  Step 4: Effect of Sample Size

# We compare different sample sizes.
for size in [5, 10, 30, 50]:
    sample_means = []

    for _ in range(1000):
        sample = np.random.choice(population, size=size, replace=True)
        sample_means.append(np.mean(sample))

    plt.figure()
    plt.hist(sample_means, bins=30)
    plt.title(f"Sampling Distribution (Sample Size = {size})")
    plt.xlabel("Sample Mean")
    plt.ylabel("Frequency")
    plt.show()

## 📌 Conclusion

# - The original population is skewed.
# - As sample size increases, the sampling distribution becomes normal.
# - This verifies the Central Limit Theorem.

## 🚀 Real-World Applications
# - Data Science
# - Machine Learning
# - Quality Control
# - Surveys and Polling





