# -*- coding: utf-8 -*-
"""Descriptive_statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-IhU-uymkEunLfeWStDzreRXpJlw6_7
"""

!pip install seaborn

import seaborn as sns
import pandas as pd

df = sns.load_dataset('tips')
df.head()

# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# basic operations
df.info()

df.describe()

df.shape

# percentiles
np.percentile(df['total_bill'],[25,50,75,90])

# Insight:
# 25% is less or equal to this bill
# 50% is middle value of the dataset
# 75% is upper portion of the dataset
# 90% is the tp 10% of bills higher than this(high spending customers)

# Quartiles and IQR
Q1=df['total_bill'].quantile(0.25)
Q3=df['total_bill'].quantile(0.75)
IQR=Q3-Q1
print(IQR)

# Insight:
# Q1 : 25%of data lies below this value
# Q3 : 75% of data lies below this pd.value_counts
# IQR : Measures the spread of middle 50% of the data

# Box plots
sns.boxplot(x=df['total_bill'])
plt.show()

# Insight:
# Box plot represents the range from  Q1 to Q3
# The line inside the box is called median
# The whiskers extends to min and max value (excluding outliers)
# The boxplot helps quickly identify outliers and understand
# the distribution of total bill values.

# Scatter plots
sns.scatterplot(x='total_bill',y='tip',data=df)
plt.show()

# Insight:
# Used to understand relationship between two variables

# Relationship:
# > Upward trend → Positive relationship
# > Downward trend → Negative relationship
# > Random pattern → No relationship

# As the total bill increases, the tip also tends to increase,
# indicating a positive relationship between the two variables.

# correlation
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.show()

# Insight:
# > Correlation measures the strength and direction of relationship
#    between variables
# > Values range from -1 to +1

# The heatmap shows that total_bill and tip have a positive correlation,
# meaning higher bills are generally associated with higher tips.

# covariance
df.cov(numeric_only=True)

# Insight:
#  Covariance shows whether two variables move together
# > Positive → move in same direction
# > Negative → move in opposite direction

# Note:
# Covariance is harder to interpret because its value depends on the
# scale of the variables and is not standardized like correlation.

# 5 Number summary
min_val = df['total_bill'].min()
Q1 = df['total_bill'].quantile(0.25)
median = df['total_bill'].median()
Q3 = df['total_bill'].quantile(0.75)
max_val = df['total_bill'].max()

five_number_summary = {
    "Minimum": min_val,
    "Q1": Q1,
    "Median": median,
    "Q3": Q3,
    "Maximum": max_val
}

five_number_summary

# Insight:
# The majority of the total bill values lie between Q1 and Q3,
# which represents the middle 50% of the data. The median indicates
# the central value of the dataset, while the minimum and maximum show the
# overall range. This summary is useful for identifying skewness and
# potential outliers in the data.

# The boxplot is a visual representation of the 5-number summary.

# Correlation v/s causation

# Correlation means two variables are related
# Causation means one variable directly affects the other

# Correlation does NOT imply causation

# Example:
# > Ice cream sales increase
# > Drowning cases increase

# -> These are correlated, but:
# Ice cream does NOT cause drowning

# The real reason is a confounding variable → summer
# Explanation of Confounding Variable:
# -> A confounding variable is an external factor that influences both variables, creating a false impression of a direct relationship.

# Insight:
# It is important to avoid assuming cause-and-effect relationships based
# only on correlation without further analysis.



