# -*- coding: utf-8 -*-
"""Intro_to _Stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXSpN3D6WZ5x7DHzUs5ZB0Pfv-KlMhgx
"""

# BASICS OF STATISTICS FOR DATA SCIENCE

# importing libraries
import numpy as np
import pandas as pd

# Create Dataset
data = [10,20,30,40,50,60,100]

# mean
np.mean(data)
# Mean gives average of the dataset.
# It is calculated by adding all values divided by total values

#median
np.median(data)
# Median is where data is arranged in ascending order.
# Not affected by outliers

# mode
from scipy import stats
stats.mode(data)
# Mode means most frequent value in dataset

#Trimmed mean
from scipy.stats import trim_mean
trim_mean(data,0.1)
# Trimmed mean is the average calculated after removing a certain percentage of the smallest and largest values.
#It reduces the effect of outliers.

# weighed mean
weights = [1, 2, 3, 4, 5,6, 1]
np.average(data, weights=weights)
# Weighted mean is an average where each value has a weight (importance).
# Values with higher weights influence the result more.

# Dispersion Measures
# Range
max(data)-min(data)
# Range shows the spread of data by calculating the difference between the maximum and minimum values.

# Variance
np.var(data)
#Variance measures how much the data values deviate from the mean.
#It uses squared differences, so values are always positive.

# Standard deviation
np.std(data)
# Standard deviation shows how far the data values are from the mean on average.
# It is the square root of variance and is widely used.

# Coefficient of Variation
(np.std(data)/np.mean(data))*100
# Coefficient of variation measures the relative variability of data as a percentage.
# It helps compare consistency between datasets.

# Frequency Concepts
df = pd.DataFrame(data, columns=["Values"])
df["Frequency"] = 1
df["Cumulative Frequency"] = df["Frequency"].cumsum()
df
#Cumulative frequency is the running total of frequencies, showing how values accumulate over time.
#Relative frequency shows how often a value occurs compared to the total number of observations.

# Final conclusion
# This notebook demonstrates basic statistical concepts and their implementation using Python.
# It helps in understanding data distribution, central tendency, and variability.





