# -*- coding: utf-8 -*-
"""Non_gaussian_Prababiility_Distributions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlAOmF4l6bdGP29eLiH4Eh_G0edlssd7
"""

# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.preprocessing import PowerTransformer

# Python Code for Kurtosis
import numpy as np
from scipy.stats import kurtosis

data = np.random.normal(0, 1, 1000)

# Kurtosis calculation
k = kurtosis(data)

print("Kurtosis:", k)

# Visualizing Different Kurtosis Types
import numpy as np
import matplotlib.pyplot as plt

# Mesokurtic (Normal)
normal = np.random.normal(0, 1, 1000)

# Leptokurtic (heavy tails)
lepto = np.random.laplace(0, 1, 1000)

# Platykurtic (flat)
platy = np.random.uniform(-3, 3, 1000)

plt.hist(normal, bins=30, alpha=0.5, label="Mesokurtic")
plt.hist(lepto, bins=30, alpha=0.5, label="Leptokurtic")
plt.hist(platy, bins=30, alpha=0.5, label="Platykurtic")

plt.legend()
plt.title("Types of Kurtosis")
plt.show()

# Normal Distribution
data = np.random.normal(loc=0, scale=1, size=1000)

plt.hist(data, bins=30, density=True, alpha=0.6)
plt.title("Normal Distribution")
plt.show()

# Log-Normal Distribution
data = np.random.lognormal(mean=0, sigma=1, size=1000)

plt.hist(data, bins=30, density=True, alpha=0.6)
plt.title("Log-Normal Distribution")
plt.show()

# Pareto Distribution
data = np.random.pareto(a=3, size=1000)

plt.hist(data, bins=30, density=True, alpha=0.6)
plt.title("Pareto Distribution")
plt.show()

# Uniform Distribution
data = np.random.uniform(low=0, high=10, size=1000)

plt.hist(data, bins=30, density=True, alpha=0.6)
plt.title("Uniform Distribution")
plt.show()

# Log Transformation
data = np.random.randint(1, 100, 1000)

log_data = np.log(data)
plt.hist(log_data, bins=30, density=True, alpha=0.6)
plt.title("Log Transformed Data")
plt.show()

# Square Root Transformation
sqrt_data = np.sqrt(data)

plt.hist(sqrt_data, bins=30, density=True, alpha=0.6)
plt.title("Square Root Transformed Data")
plt.show()

# Reciprocal Transformation
reciprocal_data = 1 / data

plt.hist(reciprocal_data, bins=30, density=True, alpha=0.6)
plt.title("Reciprocal Transformed Data")
plt.show()

# Q–Q Plot (Normality Check)
data = np.random.normal(loc=0, scale=1, size=100)

stats.probplot(data, dist="norm", plot=plt)

plt.title("Q-Q Plot")
plt.show()

# Box–Cox Transformation
data = np.random.randint(1, 100, 100)

transformed_data, lambda_value = stats.boxcox(data)

print("Best Lambda:", lambda_value)

plt.hist(transformed_data, bins=30, density=True, alpha=0.6)
plt.title("Box-Cox Transformed Data")
plt.show()

# Yeo–Johnson Transformation
data = np.array([10, 20, -5, 0, 15, -10, 25]).reshape(-1, 1)

pt = PowerTransformer(method='yeo-johnson')

transformed_data = pt.fit_transform(data)

print(transformed_data)

plt.hist(transformed_data, bins=10, density=True, alpha=0.6)
plt.title("Yeo-Johnson Transformed Data")
plt.show()

# Final Conclusion:

# Statistical distributions help describe how data is spread in real-world scenarios like normal, log-normal, Pareto, and uniform distributions.
# Data transformations such as log, square root, reciprocal, Box–Cox, and Yeo–Johnson are used to reduce skewness and stabilize variance.
# These transformations help make data more suitable for statistical analysis and machine learning models.
# Kurtosis measures the shape of a distribution in terms of peak and tail heaviness, helping to identify outliers.
# Based on kurtosis, distributions are classified into mesokurtic, leptokurtic, and platykurtic types, which help understand data behavior better.



