# -*- coding: utf-8 -*-
"""Probability_Distributions_Functions_PDF_PMF_CDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0PvVmGoGU4NU0ZULTJSUhB3ho2g8Nm3
"""

# 📊 Probability Distributions & Density Estimation using Python

## 📌 Overview
# This project explores fundamental concepts of probability
# including random variables, probability distributions, PMF, PDF, CDF, and density estimation
# using Python.

---

## 🎯 Objectives
# - Understand probability distributions
# - Visualize data using histogram and KDE
# - Learn PMF, PDF, and CDF concepts
# - Estimate distribution using density estimation

# Import Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Dataset
df = sns.load_dataset('tips')
df.head()

# Histogram
sns.histplot(df['total_bill'])
plt.title("Histogram of Total Bill")
plt.show()

### Insight:
# A histogram shows the distribution of the total_bill values.
# It helps understand how frequently values occur in different ranges.

# KDE Plot
sns.kdeplot(df['total_bill'])
plt.title("KDE Plot of Total Bill")
plt.show()

### Insight
# KDE provides a smooth curve representing the distribution of the data.
# It is more informative than a histogram as it removes noise and shows the overall pattern.

# Histogram + KDE
sns.histplot(df['total_bill'], kde=True)
plt.title("Histogram with KDE")
plt.show()

# Insight:

#The histogram shows the raw distribution, while KDE provides a smooth estimate of the same data.
# Together, they help in better understanding the distribution.

# PMF (Discrete Example)
pmf = df['size'].value_counts(normalize=True)
pmf

### Insight:
# PMF is used for discrete variables and shows the probability of each value.
# Here, it represents the probability of different group sizes.

# PDF Explanation

### Probability Density Function (PDF)
# PDF is used for continuous variables.
# It represents the density of probability rather than exact probability.
# The probability is calculated as the area under the curve.

# CDF Plot

x = np.sort(df['total_bill'])
y = np.arange(len(x)) / len(x)

plt.plot(x, y)
plt.xlabel("Total Bill")
plt.ylabel("CDF")
plt.title("Cumulative Distribution Function")
plt.show()

# Insight:
###  Cumulative Distribution Function (CDF)
# CDF shows the cumulative probability up to a given value.
# It represents the probability that a variable is less than or equal to a specific value.

# Density Estimation

#Density estimation is used to estimate the distribution of data.

#### Types:
#1. Parametric Density Estimation
#- Assumes a known distribution (e.g., Normal distribution)

#2. Non-Parametric Density Estimation
#- Does not assume any distribution

#### Kernel Density Estimation (KDE)
# KDE is a non-parametric method that creates a smooth curve from data points to estimate the distribution.

## 🔍 Key Insights

# - Most total bill values are concentrated within a specific range
# - KDE provides a smoother understanding of data distribution
# - Histogram and KDE together help in better visualization
# - PMF shows probability of discrete variables
# - CDF helps in understanding cumulative probability





